import { Hono } from "hono";
import { serveStatic } from "hono/deno";
import { useSession } from "npm:@hono/session";
import { getClaim } from "./auth/claim.ts";
import { useRootLogin } from "./routes/root/login.ts";
import { useRootLogout } from "./routes/root/logout.ts";
import { useCoachLogout } from "./routes/coach/logout.ts";
import { useStudentLogout } from "./routes/student/logout.ts";
import { useAdminLogout } from "./routes/admin/logout.ts";
import { useRootHome } from "./routes/root/home.ts";
import { useApiGetAllCampuses } from "./routes/api/campus/all.ts";
import { rootAuth } from "./auth/root.ts";
import { userAuth } from "./auth/user.ts";
import { useRootCampuses } from "./routes/root/campus.ts";
import { useRootAdmins } from "./routes/root/admin.ts";
import { useApiGetAllAdmins } from "./routes/api/root/admin/all.ts";
import { useApiAddAdmin } from "./routes/api/root/admin/add.ts";
import { useApiAddCampus } from "./routes/api/root/campus/add.ts";
import { useApiRootLogin } from "./routes/api/root/login.ts";
import { useAdminLogin } from "./routes/admin/login.ts";
import { useApiAdminLogin } from "./routes/api/admin/login.ts";
import { useStudentLogin } from "./routes/student/login.ts";
import { useApiStudentLogin } from "./routes/api/student/login.ts";
import { useCoachLogin } from "./routes/coach/login.ts";
import { useApiCoachLogin } from "./routes/api/coach/login.ts";
import { useStudentRegister } from "./routes/student/register.ts";
import { useApiStudentRegister } from "./routes/api/student/register.ts";
import { useCoachRegister } from "./routes/coach/register.ts";
import { useApiCoachRegister } from "./routes/api/coach/register.ts";
import { adminAuth } from "./auth/admin.ts";
import { studentAuth } from "./auth/student.ts";
import { coachAuth } from "./auth/coach.ts";
import { useAdminCoaches } from "./routes/admin/coach.ts";
import { useApiAdminCoachPending } from "./routes/api/admin/coach/pending.ts";
import { useApiApproveCoach } from "./routes/api/admin/coach/approve.ts";
import { useAdminHome } from "./routes/admin/home.ts";
import { useAdminTableAdd } from "./routes/admin/table/add.ts";
import { useAdminTableAll } from "./routes/admin/table/all.ts";
import { useApiAdminTableAdd } from "./routes/api/admin/table/add.ts";
import { useApiAdminTableAll } from "./routes/api/admin/table/all.ts";
import { useApiStudentMe } from "./routes/api/student/me.ts";
import { useStudentProfile } from "./routes/student/profile.ts";
import { useApiCoachMe } from "./routes/api/coach/me.ts";
import { useCoachProfile } from "./routes/coach/profile.ts";
import { useStudentHome } from "./routes/student/home.ts";
import { useCoachHome } from "./routes/coach/home.ts";
import { useStudentPassword } from "./routes/student/password.ts";
import { useApiStudentPassword } from "./routes/api/student/password.ts";
import { useCoachPassword } from "./routes/coach/password.ts";
import { useApiCoachPassword } from "./routes/api/coach/password.ts";
import { useCoachAvatar } from "./routes/coach/avatar.ts";
import { useApiCoachAvatar } from "./routes/api/coach/avatar.ts";
import { useStudentEdit } from "./routes/student/edit.ts";
import { useApiStudentEdit } from "./routes/api/student/edit.ts";
import { useCoachEdit } from "./routes/coach/edit.ts";
import { useApiCoachEdit } from "./routes/api/coach/edit.ts";
import { useStudentCoachSearch } from "./routes/student/coach/search.ts";
import { useApiStudentCoachSearch } from "./routes/api/student/coach/search.ts";
import { useApiStudentSelectCoach } from "./routes/api/student/coach/select.ts";
import { useCoachSelectionPending } from "./routes/coach/selection/pending.ts";
import { useApiCoachSelectionPending } from "./routes/api/coach/selection/pending.ts";
import { useApiCoachSelectionApprove } from "./routes/api/coach/selection/approve.ts";
import { useApiCoachSelectionReject } from "./routes/api/coach/selection/reject.ts";
import { useStudentSelectionAll } from "./routes/student/selection/all.ts";
import { useApiStudentSelectionAll } from "./routes/api/student/selection/all.ts";
import { useStudentNotifications } from "./routes/student/notifications.ts";
import { useApiStudentNotifications } from "./routes/api/student/notifications.ts";
import { useApiStudentNotificationsMarkRead } from "./routes/api/student/notifications/mark-read.ts";
import { useCoachNotifications } from "./routes/coach/notifications.ts";
import { useApiCoachNotifications } from "./routes/api/coach/notifications.ts";
import { useApiCoachNotificationsMarkRead } from "./routes/api/coach/notifications/mark-read.ts";
import { useApiStudentHome } from "./routes/api/student/home.ts";
import { useApiCoachHome } from "./routes/api/coach/home.ts";
import { useApiCoachStudents } from "./routes/api/coach/students.ts";
import { useCoachStudents } from "./routes/coach/students.ts";
import { useApiCoachTimeslotAll } from "./routes/api/coach/timeslot/all.ts";
import { useApiCoachTimeslotAdd } from "./routes/api/coach/timeslot/add.ts";
import { useApiStudentCoachTimeslots } from "./routes/api/student/coach/timeslots.ts";
import { useCoachTimeslotAll } from "./routes/coach/timeslot/all.ts";
import { useCoachTimeslotAdd } from "./routes/coach/timeslot/add.ts";
import { useApiStudentMeCoaches } from "./routes/api/student/me/coaches.ts";
import { useStudentAppointmentSearch } from "./routes/student/appointment/search.ts";
import { useApiStudentTableAvailable } from "./routes/api/student/table/available.ts";
import { useApiStudentAppointmentBook } from "./routes/api/student/appointment/book.ts";
import { useApiStudentAppointmentAll } from "./routes/api/student/appointment/all.ts";
import { useApiCoachAppointmentPending } from "./routes/api/coach/appointment/pending.ts";
import { useApiCoachAppointmentApprove } from "./routes/api/coach/appointment/approve.ts";
import { useApiCoachAppointmentReject } from "./routes/api/coach/appointment/reject.ts";
import { useCoachAppointmentPending } from "./routes/coach/appointment/pending.ts";
import { useStudentAppointmentAll } from "./routes/student/appointment/all.ts";
import { useApiCoachAppointmentAll } from "./routes/api/coach/appointment/all.ts";
import { useCoachAppointmentAll } from "./routes/coach/appointment/all.ts";
import { useApiStudentAppointmentCancel } from "./routes/api/student/appointment/cancel.ts";
import { useApiCoachAppointmentCancel } from "./routes/api/coach/appointment/cancel.ts";
import { useApiCoachAppointmentCancelling } from "./routes/api/coach/appointment/cancelling.ts";
import { useCoachAppointmentCancelling } from "./routes/coach/appointment/cancelling.ts";
import { useApiStudentAppointmentCancelling } from "./routes/api/student/appointment/cancelling.ts";
import { useStudentAppointmentCancelling } from "./routes/student/appointment/cancelling.ts";
import { useApiCoachApproveCancellation } from "./routes/api/coach/appointment/cancel/approve.ts";
import { useApiStudentApproveCancellation } from "./routes/api/student/appointment/cancel/approve.ts";

const app = new Hono();

app.use("/static/avatars/*", serveStatic({ root: "./" }));

// @ts-ignore It works but types are wrong
app.use(useSession({ secret: "SkoUqVOXTewLQiZSrdgK/DFKYQHDxmTMN1m5/0M9YLw=" }));

app.use("/root/*", rootAuth);
app.use("/api/root/*", rootAuth);
app.use("/admin/*", adminAuth);
app.use("/api/admin/*", adminAuth);
app.use("/student/*", studentAuth);
app.use("/api/student/*", studentAuth);
app.use("/coach/*", coachAuth);
app.use("/api/coach/*", coachAuth);
app.use("/api/campus/*", userAuth);

useRootLogin(app);
useRootLogout(app);
useCoachLogout(app);
useStudentLogout(app);
useAdminLogout(app);
useRootHome(app);
useApiGetAllCampuses(app);
useRootCampuses(app);
useRootAdmins(app);
useApiGetAllAdmins(app);
useApiAddAdmin(app);
useApiAddCampus(app);
useApiRootLogin(app);
useAdminLogin(app);
useApiAdminLogin(app);
useStudentLogin(app);
useApiStudentLogin(app);
useCoachLogin(app);
useApiCoachLogin(app);
useCoachRegister(app);
useApiCoachRegister(app);
useStudentRegister(app);
useApiStudentRegister(app);
useAdminCoaches(app);
useApiAdminCoachPending(app);
useApiApproveCoach(app);
useAdminHome(app);
useAdminTableAdd(app);
useAdminTableAll(app);
useApiAdminTableAdd(app);
useApiAdminTableAll(app);
useApiStudentMe(app);
useStudentProfile(app);
useApiCoachMe(app);
useCoachProfile(app);
useStudentHome(app);
useCoachHome(app);
useStudentPassword(app);
useApiStudentPassword(app);
useCoachPassword(app);
useApiCoachPassword(app);
useCoachAvatar(app);
useApiCoachAvatar(app);
useStudentEdit(app);
useApiStudentEdit(app);
useCoachEdit(app);
useApiCoachEdit(app);
useStudentCoachSearch(app);
useApiStudentCoachSearch(app);
useApiStudentSelectCoach(app);
useCoachSelectionPending(app);
useApiCoachSelectionPending(app);
useApiCoachSelectionApprove(app);
useApiCoachSelectionReject(app);
useStudentSelectionAll(app);
useApiStudentSelectionAll(app);
useStudentNotifications(app);
useApiStudentNotifications(app);
useApiStudentNotificationsMarkRead(app);
useCoachNotifications(app);
useApiCoachNotifications(app);
useApiCoachNotificationsMarkRead(app);
useApiStudentHome(app);
useApiCoachHome(app);
useApiCoachStudents(app);
useCoachStudents(app);
useCoachTimeslotAll(app);
useApiCoachTimeslotAll(app);
useCoachTimeslotAdd(app);
useStudentAppointmentSearch(app);
useApiStudentMeCoaches(app);
useApiStudentCoachTimeslots(app);
useApiCoachTimeslotAdd(app);
useApiStudentTableAvailable(app);
useApiStudentAppointmentBook(app);
useApiStudentAppointmentAll(app);
useStudentAppointmentAll(app);
useApiCoachAppointmentPending(app);
useApiCoachAppointmentApprove(app);
useApiCoachAppointmentReject(app);
useCoachAppointmentPending(app);
useApiCoachAppointmentAll(app);
useCoachAppointmentAll(app);
useApiStudentAppointmentCancel(app);
useApiCoachAppointmentCancel(app);
useApiCoachAppointmentCancelling(app);
useCoachAppointmentCancelling(app);
useApiStudentAppointmentCancelling(app);
useStudentAppointmentCancelling(app);
useApiCoachApproveCancellation(app);
useApiStudentApproveCancellation(app);

app.get("/", async (c) => {
  const claim = await getClaim(c);
  return c.json(claim);
});

Deno.serve(app.fetch);
