import { Hono } from "hono";
import { useSession } from "npm:@hono/session";
import { getClaim } from "./auth/claim.ts";
import { useRootLogin } from "./routes/root/login.ts";
import { useRootLogout } from "./routes/root/logout.ts";
import { useRootHome } from "./routes/root/home.ts";
import { useApiGetAllCampuses } from "./routes/api/campus/all.ts";
import { rootAuth } from "./auth/root.ts";
import { userAuth } from "./auth/user.ts";
import { useRootCampuses } from "./routes/root/campus.ts";
import { useRootAdmins } from "./routes/root/admin.ts";
import { useApiGetAllAdmins } from "./routes/api/root/admin/all.ts";
import { useApiAddAdmin } from "./routes/api/root/admin/add.ts";
import { useApiAddCampus } from "./routes/api/root/campus/add.ts";
import { useApiRootLogin } from "./routes/api/root/login.ts";
import { useAdminLogin } from "./routes/admin/login.ts";
import { useApiAdminLogin } from "./routes/api/admin/login.ts";
import { useStudentLogin } from "./routes/student/login.ts";
import { useApiStudentLogin } from "./routes/api/student/login.ts";
import { useCoachLogin } from "./routes/coach/login.ts";
import { useApiCoachLogin } from "./routes/api/coach/login.ts";
import { useStudentRegister } from "./routes/student/register.ts";
import { useApiStudentRegister } from "./routes/api/student/register.ts";
import { useCoachRegister } from "./routes/coach/register.ts";
import { useApiCoachRegister } from "./routes/api/coach/register.ts";
import { adminAuth } from "./auth/admin.ts";
import { studentAuth } from "./auth/student.ts";
import { coachAuth } from "./auth/coach.ts";
import { useAdminCoaches } from "./routes/admin/coach.ts";
import { useApiGetCoaches } from "./routes/api/admin/coach/pending.ts";
import { useApiApproveCoach } from "./routes/api/admin/coach/approve.ts";
import { useAdminHome } from "./routes/admin/home.ts";
import { useApiStudentMe } from "./routes/api/student/me.ts";
import { useStudentProfile } from "./routes/student/profile.ts";
import { useApiCoachMe } from "./routes/api/coach/me.ts";
import { useCoachProfile } from "./routes/coach/profile.ts";

const app = new Hono();

app.use(useSession({ secret: "SkoUqVOXTewLQiZSrdgK/DFKYQHDxmTMN1m5/0M9YLw=" }));

app.use("/root/*", rootAuth);
app.use("/api/root/*", rootAuth);
app.use("/admin/*", adminAuth);
app.use("/api/admin/*", adminAuth);
app.use("/student/*", studentAuth);
app.use("/api/student/*", studentAuth);
app.use("/coach/*", coachAuth);
app.use("/api/coach/*", coachAuth);
app.use("/api/getAllCampuses", userAuth);
app.use("/campuses", userAuth);

useRootLogin(app);
useRootLogout(app);
useRootHome(app);
useApiGetAllCampuses(app);
useRootCampuses(app);
useRootAdmins(app);
useApiGetAllAdmins(app);
useApiAddAdmin(app);
useApiAddCampus(app);
useApiRootLogin(app);
useAdminLogin(app);
useApiAdminLogin(app);
useStudentLogin(app);
useApiStudentLogin(app);
useCoachLogin(app);
useApiCoachLogin(app);
useCoachRegister(app);
useApiCoachRegister(app);
useStudentRegister(app);
useApiStudentRegister(app);
useAdminCoaches(app);
useApiGetCoaches(app);
useApiApproveCoach(app);
useAdminHome(app);
useApiStudentMe(app);
useStudentProfile(app);
useApiCoachMe(app);
useCoachProfile(app);

app.get("/", async (c) => {
  const claim = await getClaim(c);
  return c.json(claim);
});

Deno.serve(app.fetch);
